authentication/urls.py
from django.urls import path
from . import views as v

app_name = 'auth'
urlpatterns = [
    path('logout', v.logout_view, name='logout'),
    path('', v.login_view, name='authPage'),
]

csgotrademarket/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('', include('authentication.urls', namespace='auth')),
    path('', include('market.urls', namespace='market')),
]

market/urls.py
from django.urls import path
from . import views as v

app_name = 'market'
urlpatterns = [
    path('market', v.market_main_view, name='market_main'),
    path('update', v.update_inventory, name='update_inventory'),
    path('my_inventory', v.get_user_inventory, name='my_inventory'),
]

authentication/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


class SteamUserManager(BaseUserManager):
    def _create_user(self, steamid, password, **extra_fields):
        """
        Creates and saves a User with the given steamid and password.
        """
        try:
            # python social auth provides an empty email param, which cannot be used here
            del extra_fields['email']
        except KeyError:
            pass
        if not steamid:
            raise ValueError('The given steamid must be set')
        user = self.model(steamid=steamid, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, steamid, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(steamid, password, **extra_fields)

    def create_superuser(self, steamid, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(steamid, password, **extra_fields)


class SteamUser(AbstractBaseUser, PermissionsMixin):
    USERNAME_FIELD = 'steamid'

    steamid = models.CharField(max_length=17, unique=True)
    personaname = models.CharField(max_length=255)
    profileurl = models.CharField(max_length=300)
    avatar = models.CharField(max_length=255)
    avatarmedium = models.CharField(max_length=255)
    avatarfull = models.CharField(max_length=255)

    # Add the other fields that can be retrieved from the Web-API if required

    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = SteamUserManager()

    def get_short_name(self):
        return self.personaname

    def get_full_name(self):
        return self.personaname

    def get_steam_id(self):
        return self.steamid

market/models.py
from django.db import models

# Модель оружия, в полях модели всякие параметры из стима


class Weapon(models.Model):

	bot = models.ForeignKey('Bot', on_delete=models.CASCADE, null=True)
	steam_id = models.IntegerField()
	classid = models.IntegerField()
	instanceid = models.IntegerField()
	appid = models.IntegerField()
	tradable_after = models.TextField()
	exterior = models.CharField(max_length=200)
	icon_url = models.TextField()
	market_hash_name = models.CharField(max_length=200)
	market_name = models.CharField(max_length=200)
	marketable = models.IntegerField()
	name = models.CharField(max_length=200)
	tradable = models.IntegerField()
	type = models.CharField(max_length=200)

	def __str__(self):
		return self.name

# Модель бота маркета, содержащая данные логина, пароля, данных steam guard и апи ключ от стим


class Bot(models.Model):
	login = models.CharField(max_length=50)
	password = models.CharField(max_length=50)
	steam_guard_name = models.CharField(max_length=200)
	api_key = models.CharField(max_length=100)
	link = models.CharField(max_length=200, null='steam url')

	def __str__(self):
		return self.login

authentication/views.py
from django.contrib.auth import logout as auth_logout
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


def login_view(request):
	name1 = 'wqdf gdfvsdawee rewfe'
	return render(request, 'authentication/authPage.html', {'name': name1})


@login_required
def logout_view(request):
	auth_logout(request)
	return redirect('auth:authPage')

market/views.py
from authentication.models import SteamUser
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from steampy.client import SteamClient, InvalidCredentials
from steampy.utils import GameOptions
from .models import Bot, Weapon
import os


def bot_inventory():
	bot = Bot.objects.all()[0]
	API_KEY = bot.api_key
	LOGIN = bot.login
	PASSWORD = bot.password
	steam_guard_name = bot.steam_guard_name
	steam_guard_path = r'C:\Users\timag\Desktop\marketproj\csgotrademarket\market\steam_guard.txt'
	steam_client = SteamClient(API_KEY)
	try:
		steam_client.login(LOGIN, PASSWORD, steam_guard_path)
	except (ValueError, InvalidCredentials):
		print('Your login credentials are invalid')
		#exit(1)
	#print("Logged into steam")
	game = GameOptions.CS
	inv = steam_client.get_my_inventory(game)
	return inv


def user_inventory(request):
	bot = Bot.objects.all()[0]
	API_KEY = bot.api_key
	LOGIN = bot.login
	PASSWORD = bot.password
	steam_guard_name = bot.steam_guard_name
	steam_guard_path = r'C:\Users\timag\Desktop\marketproj\csgotrademarket\market\steam_guard.txt'
	steam_client = SteamClient(API_KEY)
	try:
		steam_client.login(LOGIN, PASSWORD, steam_guard_path)
	except (ValueError, InvalidCredentials):
		print('Your login credentials are invalid')
		#exit(1)
	#print("Logged into steam")
	game = GameOptions.CS
	inv = steam_client.get_partner_inventory(str(request.user.steamid), game)
	return inv


def get_bot_inventory():
	inv = bot_inventory()
	list_keys = list(inv.keys())
	for i in range(len(list_keys)):
		inv1 = inv[list_keys[i]]
		classid = inv1['classid']
		instanceid = inv1['instanceid']
		appid = inv1['appid']
		descriptions1 = inv1['descriptions']
		# descriptions = inv['descriptions'][2]

		exterior = descriptions1[0]['value'].split(' ')[1]
		icon_url = 'https://steamcommunity-a.akamaihd.net/economy/image/'+inv1['icon_url']
		market_hash_name = inv1['market_hash_name']
		market_name = inv1['market_name']
		marketable = inv1['marketable']
		name = inv1['name']
		type = inv1['type']
		tradable = inv1['tradable']
		tags = inv1['tags']
		steam_id = inv1['id']
		if int(tradable) == 0:
			try:
				tradable_after = inv1['owner_descriptions'][1]['value']
			except KeyError:
				tradable_after = 'null'
		else:
			tradable_after = '0'
		if Weapon.objects.filter(bot=Bot.objects.all()[0], classid=classid, appid=appid, instanceid=instanceid,
							  exterior=exterior, icon_url=icon_url, market_hash_name=market_hash_name, market_name=market_name,
							  name=name, type=type, marketable=marketable, steam_id=steam_id, tradable_after=tradable_after, tradable=tradable).exists():
			pass
		else:
			Weapon.objects.create(bot=Bot.objects.all()[0], classid=classid, appid=appid, instanceid=instanceid,
							  exterior=exterior, icon_url=icon_url, market_hash_name=market_hash_name, market_name=market_name,
							  name=name, type=type, marketable=marketable, steam_id=steam_id, tradable_after=tradable_after, tradable=tradable)
	return 0


def update_inventory(request):
	get_bot_inventory()
	return redirect('market:market_main')


@login_required
def get_user_inventory(request):
	ui = user_inventory(request)
	#ui = request.user.steamid
	return render(request, 'market/my_inv.html', {'bot': ui})


def market_main_view(request):
	weapons = Weapon.objects.all()
	item_list = []
	for weapon in weapons:
		item_list.append({'name': weapon.market_name, 'exterior': weapon.exterior, 'tradable': weapon.tradable_after, 'icon': weapon.icon_url})

	return render(request, 'market/main.html', {'bot': item_list})

templates/authentication/authPage.html
{% extends "wrapper.html" %}

{% block auth %}
    {% if user.is_authenticated %}
        <a  href="{% url "auth:logout" %}" class="btn btn_header">
             <li class="btn_item">
                <img src="static/authentication/image/steamLogo.png" alt="steam">
            </li>
            <li class="btn_item">
            Выйти из Steam
            </li>
        </a>
<!--        <br>-->
<!--        Hello, {{ user.personaname }}-->
<!--        <br>-->
<!--        {{ name }}-->
    {% else %}
        <a  href="{% url "social:begin" "steam" %}" class="btn btn_header">
            <li class="btn_item">
                <img src="static/authentication/image/steamLogo.png" alt="steam">
            </li>
            <li class="btn_item">
            Войти через Steam
            </li>
        </a>
    {% endif %}
{% endblock %}

templates/market/main.html
{% extends "wrapper.html" %}
{% block auth %}
    {% if user.is_authenticated %}
        <a  href="{% url "auth:logout" %}" class="btn btn_header">
             <li class="btn_item">
                <img src="static/authentication/image/steamLogo.png" alt="steam">
            </li>
            <li class="btn_item">
            Выйти из Steam
            </li>
        </a>
<!--        <br>-->
<!--        Hello, {{ user.personaname }}-->
<!--        <br>-->
<!--        {{ name }}-->
    {% else %}
        <a  href="{% url "social:begin" "steam" %}" class="btn btn_header">
            <li class="btn_item">
                <img src="static/authentication/image/steamLogo.png" alt="steam">
            </li>
            <li class="btn_item">
            Войти через Steam
            </li>
        </a>
    {% endif %}
{% endblock %}
{% block info %}
    {% if user.is_authenticated %}<a  href="{% url "market:my_inventory" %}">Мой Инвентарь</a>{% endif %}<br><br>
    <a  href="{% url "market:update_inventory" %}">Обновить инвентарь маркета</a>
    <ul>
    {% for item in bot %}
        <li><img width = "170" height = "125" src="{{ item.icon }}"> {{ item.name }}    {{ item.exterior }}    {{ item.tradable }}</li>
    {% endfor %}
    </ul>

{% endblock %}

templates/market/my_inv.html
{% extends "wrapper.html" %}
{% block auth %}
    {% if user.is_authenticated %}
        <a  href="{% url "auth:logout" %}" class="btn btn_header">
             <li class="btn_item">
                <img src="static/authentication/image/steamLogo.png" alt="steam">
            </li>
            <li class="btn_item">
            Выйти из Steam
            </li>
        </a>
<!--        <br>-->
<!--        Hello, {{ user.personaname }}-->
<!--        <br>-->
<!--        {{ name }}-->
    {% else %}
        <a  href="{% url "social:begin" "steam" %}" class="btn btn_header">
            <li class="btn_item">
                <img src="static/authentication/image/steamLogo.png" alt="steam">
            </li>
            <li class="btn_item">
            Войти через Steam
            </li>
        </a>
    {% endif %}
{% endblock %}
{% block info %}
    <a  href="{% url "market:update_inventory" %}">Обновить инвентарь маркета</a><br><br>
    {% if user.is_authenticated %}<a  href="{% url "market:my_inventory" %}">Мой Инвентарь</a>{% endif %}
    <ul>
    {{ bot }}
    </ul>

{% endblock %}

templates/wrapper.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Заголовок страницы</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600,700&display=swap" rel="stylesheet">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" type="text/css">
</head>
<body>
    <header class="header" id="header">
        <!--<div class="pic"></div>-->
        <div class="container">
            <div class="nav">
                <ul class="menu">
                    <li class="menu_item">
                        <a href="#">Как это работает?</a>
                    </li>
                    <li class="menu_item">
                        <a href="#">FAQ</a>
                    </li>
                    <li class="menu_item">
                        <a href="#">Боты</a>
                    </li>
                    <li class="menu_item">
                        <a href="{% url "market:market_main" %}">
                        Открыть магазин
                    </a>
                    </li>
                </ul>
                <a href="{% url "market:market_main" %}" class="logo">
                    <img src="{% static 'authentication/image/mainLogo.png' %}" alt="CSGOTRADEMARKET">
                </a>
                {% block auth %}
                {% endblock %}
            </div>
            <div class="offer">
                <div class="offer_content">
                    <!--<div class="offer_intro">
                        Скины по самым выгодным ценам
                    </div>
                    <p class="offer_title">
                        СКИДКИ ДО 50%
                    </p>-->
                    {% block info %}
                    {% endblock %}
                    <a href="{% url "market:market_main" %}" class="btn-shop btn-shop_header">
                        Открыть магазин
                    </a>
                    <!--<div class="item_price_old">
                        3800 ₽
                    </div>
                    <div class="item_price_new">
                        1900 ₽
                    </div>-->
                </div>
            </div>
        </div>

    </header>
    <section class="features" id="features">
        <div class="container">
            <ul class="features_list">
                <li class="features_item">
                    <img src="{% static 'authentication/image/time.png' %}" alt="time">
                </li>
                <li class="features_item">
                    <img src="{% static 'authentication/image/gun.png' %}" alt="gun">
                </li>
                <li class="features_item">
                    <img src="{% static 'authentication/image/safe.png' %}" alt="safe">
                </li>
            </ul>
        </div>
    </section>
    <section class="info" id="info">
        <div class="container">
            <div class="nav">
                <div class="smallLogo">
                    <img src="{% static 'authentication/image/logo.png' %}" alt="logo">
                    <div class="smallLogoText">
                        Обмен скинов cs go. Все права защищены.
                        Данный сайт не является частью корпорации valve.
                    </div>
                </div>
                <ul class="smallMenu">
                    <li class="smallMenu_text">
                        Разделы
                    </li>
                    <li class="smallMenu_item">
                        <a href="#">Обмен скинов</a>
                    </li>
                    <li class="smallMenu_item">
                        <a href="#">Трейд площадка</a>
                    </li>
                    <li class="smallMenu_item">
                        <a href="#">FAQ</a>
                    </li>
                    <li class="smallMenu_item">
                        <a href="#">Боты</a>
                    </li>
                </ul>
                <div class="payLogo">
                     <img src="{% static 'authentication/image/payment.png' %}" alt="payment">
                </div>
                <div class="links">
                    <img src="{% static 'authentication/image/links.png' %}" alt="links">
                </div>
            </div>
        </div>
    </section>
</body>
</html>